### ISSUE TITLE
print()函数的官方文档，sep现在有空格了

### ISSUE THREAD

**Issue by linxixizhi** [selfteaching/the-craft-of-selfteaching#111]
Part.1.E.4中的脚注提到：

> print() 函数的官方文档里，sep='' 肯定是 sep=' ' 的笔误 —— 可以用以下代码验证（2019.02.14）

而现在（2019.03.16）复制粘贴文档中的`sep=' '`，会发现是有空格的。

这是改了么？

**Comment by xiaolai** [comment]
https://bugs.python.org/issue35986

**Comment by linxixizhi** [comment]
明白了，是本来就有。只是排版的选择上出了点问题，导致显示得像没有一样。那这个脚注需要更改么？

**Comment by xiaolai** [comment]
在这个 commit 里面，我做了一点修订： https://github.com/selfteaching/the-craft-of-selfteaching/commit/5ec732f9870f04da8b8fd37285de48d2365314ac#diff-e376ac2122b41e60df078c27fe78d0c3

**Comment by LALINUX2019** [comment]
噗~看了文档，还真是跟没有空格一样一样的。
那官方都不能改个字体么

**Comment by DHclly** [comment]
新版样式：
<img width="855" height="117" alt="Image" src="https://github.com/user-attachments/assets/3752539a-557f-4e87-bd66-4e8071d38501" />
原版样式：

<img width="1558" height="496" alt="Image" src="https://github.com/user-attachments/assets/ef32b038-5906-4d96-a0d7-936043b9e876" />

还别说，没加等宽字体样式还真看着差别不大😂😂😂
