### ISSUE TITLE
关于jupyter lab配置成系统服务时候

### ISSUE THREAD

**Issue by chargemyself** [selfteaching/the-craft-of-selfteaching#117]
launchctl load 终端会报错， launchctl 不是内部或外部命令，也不是可运行程序，或批处理文件。
这个实在不知道怎么解决，google了，我是win10系统

**Comment by xiaolai** [comment]
哦，这里的处理方式，是 mac os 的。windows 上请参考 https://stackoverflow.com/questions/51036132/running-jupyterlab-as-a-desktop-application-in-windows-10

**Comment by xiaolai** [comment]
关于 windows 用户可能遇到的问题，我还在收集。回头一并处理。

**Comment by chargemyself** [comment]
谢谢笑来老师。

**Comment by lihaotian007** [comment]
果然issue比较好用，Google了一上午发现这个不是win10的命令，然后issue了一下就有结果了，哈哈哈

**Comment by YangQinghan** [comment]
我还是不知道怎么解决呢 = =
按照下面步骤首先我在C盘的这个位置找不到Anaconda3\Scripts. 接下来的内容就更看不懂了，求助大家。提前感谢！

> Go to the directory of C:\ProgramData\Anaconda3\Scripts
Find the file of jupyter-lab.exe and make the link of the file in Taskbars. Note: With some reasons, the message of the "Widows could not create the shortcut. Check to see if the disk is full" popped up when I tried to make the link on the Desktop.
Right click on the link of jupyter-lab.exe and go to Properties.
Download the icon file of Jupyterlab and save it as Jupyterlab.ico in the folder of C:\ProgramData\Anaconda3\Menu\Jupyterlab.ico (=`%ALLUSERSPROFILE%\Anaconda3\Menu\Jupyterlab.ico )
Click Change Icon and copy %ALLUSERSPROFILE%\Anaconda3\Menu\Jupyterlab.ico in "Look for icons in this file".

**Comment by ds-dog** [comment]
> 
> 
> 我还是不知道怎么解决呢 = =
> 按照下面步骤首先我在C盘的这个位置找不到Anaconda3\Scripts. 接下来的内容就更看不懂了，求助大家。提前感谢！
> 
> > Go to the directory of C:\ProgramData\Anaconda3\Scripts
> > Find the file of jupyter-lab.exe and make the link of the file in Taskbars. Note: With some reasons, the message of the "Widows could not create the shortcut. Check to see if the disk is full" popped up when I tried to make the link on the Desktop.
> > Right click on the link of jupyter-lab.exe and go to Properties.
> > Download the icon file of Jupyterlab and save it as Jupyterlab.ico in the folder of C:\ProgramData\Anaconda3\Menu\Jupyterlab.ico (=`%ALLUSERSPROFILE%\Anaconda3\Menu\Jupyterlab.ico )
> > Click Change Icon and copy %ALLUSERSPROFILE%\Anaconda3\Menu\Jupyterlab.ico in "Look for icons in this file".

我也是同样的问题，Google找了好久这篇也研究了一两个小时，还是解决不了。

**Comment by Nathanhan81** [comment]
对于笑来老师提供的链接里的内容，我的理解是它只是创建了一个**有可能**在window10环境下快捷启动Jupyter lab的快捷方式（亲测无法启动），后面的几步只是在更改这个快捷方式的图标以便用户识别。
但是它仍然**无法**实现如笑来老师所提供的mac系统下的系统服务的效果。
我也在Google方法，找到了这篇https://segmentfault.com/a/1190000014518848
**注意在执行如下命令时要按照下面的提示进行**
```
pip install pywin32
#然后用cd 命令 进入你安装Annaconda的目录的Scripts目录，我的是（C:\anaconda\Scripts）
cd `\scripts
python Scripts/pywin32_postinstall.py -install
```

目前在试后面的步骤

**Comment by smkwls** [comment]
> > 我还是不知道怎么解决呢 = =
> > 按照下面步骤首先我在C盘的这个位置找不到Anaconda3\Scripts. 接下来的内容就更看不懂了，求助大家。提前感谢！
> > > Go to the directory of C:\ProgramData\Anaconda3\Scripts
> > > Find the file of jupyter-lab.exe and make the link of the file in Taskbars. Note: With some reasons, the message of the "Widows could not create the shortcut. Check to see if the disk is full" popped up when I tried to make the link on the Desktop.
> > > Right click on the link of jupyter-lab.exe and go to Properties.
> > > Download the icon file of Jupyterlab and save it as Jupyterlab.ico in the folder of C:\ProgramData\Anaconda3\Menu\Jupyterlab.ico (=`%ALLUSERSPROFILE%\Anaconda3\Menu\Jupyterlab.ico )
> > > Click Change Icon and copy %ALLUSERSPROFILE%\Anaconda3\Menu\Jupyterlab.ico in "Look for icons in this file".
> 
> 我也是同样的问题，Google找了好久这篇也研究了一两个小时，还是解决不了。

笑来老师链接里的方法是在你scripts目录中找到jupyter lab.exe文件，然后右键点击创建快捷方式到桌面，但是呢这个快捷方式的图标太丑了，于是就从网上下载一个jupyter lab.icon，下载完后你再右键点击快捷方式，选择里面的更改图标，就可以替换图标，改成好看的图标了。

**Comment by Alfred212121** [comment]
> 我还是不知道怎么解决呢 = =
> 按照下面步骤首先我在C盘的这个位置找不到Anaconda3\Scripts. 接下来的内容就更看不懂了，求助大家。提前感谢！
> 
> > Go to the directory of C:\ProgramData\Anaconda3\Scripts
> > Find the file of jupyter-lab.exe and make the link of the file in Taskbars. Note: With some reasons, the message of the "Widows could not create the shortcut. Check to see if the disk is full" popped up when I tried to make the link on the Desktop.
> > Right click on the link of jupyter-lab.exe and go to Properties.
> > Download the icon file of Jupyterlab and save it as Jupyterlab.ico in the folder of C:\ProgramData\Anaconda3\Menu\Jupyterlab.ico (=`%ALLUSERSPROFILE%\Anaconda3\Menu\Jupyterlab.ico )
> > Click Change Icon and copy %ALLUSERSPROFILE%\Anaconda3\Menu\Jupyterlab.ico in "Look for icons in this file".

估计是因为软件改版和系统升级等原因，导致scripts文件夹的路径发生了变换，我这台电脑上的路径是C:\Users\username\.anaconda\navigator\scripts，其中username是你windows系统的用户名。
