### ISSUE TITLE
自学python 也需要社交，you can you up, no bb

### ISSUE THREAD

**Issue by liujuanjuan1984** [selfteaching/the-craft-of-selfteaching#136]
`you can you up, no bb` 是一句中式英文版的俗语：`你行你上啊，别哔哔`。

我弄了1个小的微信群，群的名字就叫做：`you can you up, no bb` 。**主题就是吃透笑来的这本新书，通过自学python来掌握自学能力**。

并做了一个 [应景 的小“作业集](https://github.com/liujuanjuan1984/ucanuupnobb)”，是作业集而不是教程，是因为这个过程中，有节奏地靠自学掌握技能，其实比直接拿来主义获得知识点似乎更重要。

这里没有“老师”，只有大家都在一块儿学，一块儿前行，一块儿完善 对 **从0到1 的初学者** 更友好 的 作业集。——还有，如果你想要面向 从0到1的初学者 提供一些有价值的文章，也可以进来发现有价值的场景，由此写出你有价值的文章。

这里每个人都是“老师”，因为“教是最好的学”，教自己，和尝试教会别人，都还挺需要一起练习的。

如果你暂时没有任何python相关的社交氛围，欢迎加我的微信号 qiaoanlu ，会自动通过好友，请说明来自github，想加入you can you up, no bb群。

**Comment by xiaolai** [comment]
这种群现在搞没啥意义，组织者没经验的话，也会浪费很多人时间。等大家“挑毛病”一段时间再说吧。
