### ISSUE TITLE
统一Boolean的翻译

### ISSUE THREAD

**Issue by renkelvin** [selfteaching/the-craft-of-selfteaching#148]
是否应将“布林”均统一为“布尔”，以减少初学者的疑惑
https://render.githubusercontent.com/view/ipynb?commit=f36466ef2ba6674dcd3a16917d95a2bc1e6b8875&enc_url=68747470733a2f2f7261772e67697468756275736572636f6e74656e742e636f6d2f73656c667465616368696e672f7468652d63726166742d6f662d73656c667465616368696e672f663336343636656632626136363734646364336131363931376439356132626331653662383837352f506172742e312e452e312e656e7472616e63652e6970796e62&nwo=selfteaching%2Fthe-craft-of-selfteaching&path=Part.1.E.1.entrance.ipynb&repository_id=175635390&repository_type=Repository#布林运算

**Comment by xiaolai** [comment]
好，全改过来了：

https://github.com/selfteaching/the-craft-of-selfteaching/commit/27de0cf3511e975bcac6b5255ae42875017d37fc
