### ISSUE TITLE
请问del 和 del() 有什么区别？

### ISSUE THREAD

**Issue by HarryYC** [selfteaching/the-craft-of-selfteaching#150]
在 `Part.1.E.6.containers.ipynb` 一节中， 笑来老师分别用了`del` 和 `del()` 对列表进行了操作:
```
del c_list[3]
print(c_list)           # del 是个命令，del a_list[3] 是一个语句；不能这么写： print(del a_list[3])
```
以及：
```
del(L[2])
print(L) # 用 del() 对 L 操作之后，L 本身少了 1 个元素
```
我的疑问是*del statment* 和 *del() function* 有什么区别？

我测试了用del 和 del() 对列表进行操作，发现返回的结果是一样的：

```
L1 = ['1', '2', '3']
del L1[1]
print(L1)
L2 = ['1', '2', '3']
del(L2[1])
print(L2)
```
['1', '3']
['1', '3']

在[这里](https://docs.python.org/3/tutorial/datastructures.html?highlight=del#the-del-statement) 我找到了关于del statment 的解释，但是并没有在[Built-in Functions](https://docs.python.org/3.8/library/functions.html)中找到`del()`
所以说`del()`并不是一个 Built-in Function ？在哪里可以找到关于del()的说明？

**Comment by HarryYC** [comment]
似乎找到了答案：

Normally `del` is used without parentheses, as:
```
del x
```
However, including parentheses around the argument as ```del(x)``` is allowed but doesn't mean it's a function call.

ref: https://stackoverflow.com/questions/2895629/python-del-built-in-cant-be-used-in-assignment

**Comment by xiaolai** [comment]
为了避免初学者的理解困难，我把所有的 del() 都改了，改成 del 

https://github.com/selfteaching/the-craft-of-selfteaching/commit/8aa2ca590bd06f44cda223f72af9da55d6dff511
