### ISSUE TITLE
[关于转载] 其他语言的版本发在自己的公众号上是否合适？

### ISSUE THREAD

**Issue by albertschr** [selfteaching/the-craft-of-selfteaching#17]
CC BY-NC-ND 4.0 协议中表明：
        
- 禁止演绎 — 如果您 再混合、转换、或者基于该作品创作，您不可以分发修改作品。

这是否意味着将代码块替换为其他语言版本，即使署名出处，也不能发在自己的公众号上？

**Comment by xiaolai** [comment]
最终选择了这个版权协议。就只能按照这个协议走了。

**Comment by albertschr** [comment]
> 最终选择了这个版权协议。就只能按照这个协议走了。但，写得好的话，能放在这里跟我的书一并开源。

感谢解答。
