### ISSUE TITLE
jupyter lab设置为dark theme，一些图表的图片显示不清晰

### ISSUE THREAD

**Issue by xiaominglui** [selfteaching/the-craft-of-selfteaching#175]
如下图：
<img width="930" alt="Screen Shot 2019-03-17 at 16 21 28" src="https://user-images.githubusercontent.com/1144295/54487466-26ede380-48d1-11e9-8448-ee6d1d23ec26.png">

**Comment by linxixizhi** [comment]
图片的问题，背景慢慢调成某种灰色应该能好一些。

**Comment by xiaolai** [comment]
没办法，因为几乎所有图片都做了透明背景处理，导致了这个结果。别用 darktheme 了。哈
