### ISSUE TITLE
修改两个字符，懒得提交pull request了

### ISSUE THREAD

**Issue by linxixizhi** [selfteaching/the-craft-of-selfteaching#20]
文件`Part.1.D.preparation.for.reading.md`中，有两处`《[Jupyterlab 的安装与配置](z-appendix.jupyter-installation-and-setup.ipynb)》`，`z-appendix`好像要改为`T-appendix`？

**Comment by xiaolai** [comment]
麻烦您别懒，提交一下呗…… 感谢。

**Comment by xiaolai** [comment]
好吧，我自己改了。哈哈。

**Comment by linxixizhi** [comment]
> 好吧，我自己改了。哈哈。

好的。
