### ISSUE TITLE
关于首页自学递归函数的建议

### ISSUE THREAD

**Issue by renkelvin** [selfteaching/the-craft-of-selfteaching#218]
https://github.com/selfteaching/the-craft-of-selfteaching/blob/master/00.cover.ipynb
本节最后给出了一个关于自学的递归函数，其中有几点问题。
一是这个函数无法终止。我本来以为这是“学海无涯”的意思，但后来一想，运行时间可以无限，但人的脑容量毕竟是有限的，最终还是会stackoverflow。
二是这个函数是一个标准的尾递归。尾递归理论上一定可以被loop重写，因此除了编码方便，在运行时间和空间上都没有优势，以至于一些编译器会默认优化尾递归。这里作为递归的一个示例不太合适。

建议改为：
```
def TeachYourSelf(anything):
    while not create(something):
        learn()
        if require someotherthing:
            TeachYourSelf(someotherthing)
        practice()
    return "Eureka"

TeachYourSelf(coding)
TeachYourSelf(another1)
TeachYourSelf(another2)
...
```

**Comment by xiaolai** [comment]
这个样改之后，初学者更看不懂了…… 其实是个伪代码，所以，点到为止了。
