### ISSUE TITLE
单独添加配置环境的第0章？

### ISSUE THREAD

**Issue by gantrol** [selfteaching/the-craft-of-selfteaching#222]
配置环境想“刨牛毛”一样麻烦，若有单独一章讲解，则会对没接触过Python的人友好许多。

市面上也有很多书籍供人借鉴，比如：
- 详细型：[《Python3网络爬虫开发实战》1.1-Python3的安装](https://cuiqingcai.com/5059.html)；
- 简短型：[《笨方法学Python》的练习0](https://learnpythonthehardway.org/python3/ex0.html)；

> 《笨方法学Python》是*Learn Python The Hard Way*的中文书名，个人倾向于翻译成《认真学Python》。

**Comment by xiaolai** [comment]
最后看看怎么加进去。

**Comment by wwwxj123** [comment]
这是你写给谁的邮件

JianQiu Hwang ***@***.***>於 2022年8月3日 週三，08:21寫道：
