### ISSUE TITLE
一个例子

### ISSUE THREAD

**Issue by chargemyself** [selfteaching/the-craft-of-selfteaching#252]
在讲到print（）函数的时候，举例打一个乘法口诀是极好的，随便深刻理解一下range（）这个函数。
代码如下：
```
for m in range(1,10):
	for n in range(1,m+1):
	    print (str(m) +"*"+str(n) +"="+ str(m*n)+" ",end ="")
	print()    # default  end =“\n”
```

**Comment by renbaoqi** [comment]
for m in range(1,10):
	for n in range(1,m+1):
	    print (str(m) +"*"+str(n) +"="+ str(m*n)+" ",end ="")
	print()    # default  end =“\n”
