### ISSUE TITLE
Part.1.E.7.files 在JupyterLab运行生成文件代码出错

### ISSUE THREAD

**Issue by qinfeng8848** [selfteaching/the-craft-of-selfteaching#293]
ERROR:root:Internal Python error in the inspect module. Below is the traceback from this internal error.
![](https://ws4.sinaimg.cn/large/006tKfTcly1g193j0m24cj318q0foadh.jpg)

我google也查不出问题在哪里，推测是我的JupyterLab配置的问题

**Comment by linxixizhi** [comment]
你的电脑是Max？可能跟目录、权限之类有关（我不太懂Max）。建议加上你这里的工作目录和电脑类型，这样更容易得到回复。

**Comment by xiaolai** [comment]
大致应该是你那些文件所在的目录，并没有设置“可写”权限。

**Comment by qinfeng8848** [comment]
是mac电脑，重启电脑之后，问题就不出现了。重启大法好
