### ISSUE TITLE
举报: 新生大学 强用本书内容发信在线课程

### ISSUE THREAD

**Issue by ZoomQuiet** [selfteaching/the-craft-of-selfteaching#30]
[李笑来讲座预告：如何通过python习得自学这门手艺？ 新生大学](https://mp.weixin.qq.com/s/jJgnRQ-FV-RaTUeZXV0Jpw)

是也乎,(￣▽￣)

这种直接使用开源图书组织收费课程的形式是否吻合 

[Creative Commons — 署名-非商业性使用-禁止演绎 3.0 未本地化版本 — CC BY-NC-ND 3.0](https://creativecommons.org/licenses/by-nc-nd/3.0/deed.zh)

> 建议

在正文, 或是 README 中给出正确的图书使用形式...

否则, 将有无数聪明人来试探底线的...

**Comment by linxixizhi** [comment]
商业另外授权就好了。而新生大学是李笑来老师的一个项目。。。你赶紧把这个issue关掉吧

**Comment by ZoomQuiet** [comment]
@linxixizhi 是也乎,(￣▽￣)

原来如比...明白了
