### ISSUE TITLE
Jupyter多语言支持之scijava-jupyter-kernel

### ISSUE THREAD

**Issue by gantrol** [selfteaching/the-craft-of-selfteaching#311]
今晚在Jupyter上运行了Java代码，并写了Java版的[Part.1.E.1.entrance.ipynb](https://github.com/linxixizhi/the-craft-of-selfteaching/blob/Java/Part.1.E.1.entrance.ipynb)（语句块那里没改）

是的，除了运行Python程序，Jupyter还能运行其他语言的程序。秘诀就在Jupyter的kernel。这里选择添加Java的`scijava-jupyter-kernel`

[有多种kernel可以选择](https://stackoverflow.com/questions/33972860/java-kernel-for-jupyter)，这里选择`scijava-jupyter-kernel`，它还能支持多种语言：

> Some of the supported languages are Groovy (default), Python, Beanshell, Clojure, Java, Javascript, Ruby and Scala.([detail](https://github.com/scijava/scijava-jupyter-kernel))

安装好Anaconda后，使用下列命令安装：

```shell
conda config --add channels conda-forge
conda create --name java_env scijava-jupyter-kernel
```

安装完成后，在Jupyter lab查看文档时，右上角显示的便是当前kernel，默认是Python，点击即可选择切换成`SciJava`。

**Comment by prateekrastogi** [comment]
如何下载内核流媒体艺术？

**Comment by prateekrastogi** [comment]
我在哪里可以找到可执行的内核？

**Comment by prateekrastogi** [comment]
我在哪里可以找到可执行的jupyter内核？

**Comment by linxixizhi** [comment]
@prateekrastogi 你这句话好像有几种意思，一是怎么下载安装，二是下载安装后怎么使用，三还有怎么下载其他内核……不知道你问的是哪方面的？

**Comment by prateekrastogi** [comment]
@linxixizhi 朋友，缺乏jupyter文档知识困惑和害怕我

**Comment by linxixizhi** [comment]
@prateekrastogi 

那确实不容易。你能问得更具体一些么？比如你到哪一步失败了？是下载Anaconda、安装`scijava-jupyter-kernel`还是其他的？（最好把报错也复制粘贴下，还有我觉得你用英语提问更好些？）

Yes, it's not easy. Could you ask in English with more detail? For example, where are you failed? Downloading Anaconda, installing `scijava-jupyter-kernel`, and so on?

**Comment by prateekrastogi** [comment]
相同的错误消息是[:](https://stackoverflow.com/questions/41926219/error-message-when-launching-pyspark-from-jupyter-notebook-on-windows)
Error message when launching PySpark from Jupyter notebook on Windows

**Comment by linxixizhi** [comment]
就是让Jupyter支持PySpark？我不懂这个，但我知道一些教程：

- English, Windows, Step by step: https://changhsinlee.com/install-pyspark-windows-jupyter/
- English, Mac: https://ramhiser.com/2015/02/01/configuring-ipython-notebook-support-for-pyspark/
- 中文, Windows: https://www.cnblogs.com/kongchung/p/5646608.html

Good luck.

**Comment by prateekrastogi** [comment]
thanks...
