### ISSUE TITLE
for语句块表达有误

### ISSUE THREAD

**Issue by mi4tin** [selfteaching/the-craft-of-selfteaching#341]
for n in range(2, 100):
    if n == 2:
        print(n)
        continue
    for i in range(2, n):
        if (n % i) == 0:
            print(n,'c')
            break
    print(n,'b')            # 事实上相当于针对 range(2, 100) 中每个 n 都执行了一次 print(n)
                        # 这个 print(n) 属于语句块 for n in range(2, 100): 

实际测试是continue后面的 print(n,'b')   也不会执行，break要执行。怎么感觉 都是直接忽视continue

**Comment by trialbox** [comment]
Python是对空格对齐敏感的语言。建议笑来老师在这个例子中重点说明。
@mi4tin 贴python代码的时候用键盘波浪线下(tab键上方)前后三个"`"包起来。
```
for n in range(2, 100):
    if n == 2:
        print(n)
        continue
    for i in range(2, n):
        if (n % i) == 0:
            break
    print(n)            # 事实上相当于针对 range(2, 100) 中每个 n 都执行了一次 print(n)
                        # 这个 print(n) 属于语句块 for n in range(2, 100):
```

**Comment by mi4tin** [comment]
···if 
   else 
···

**Comment by mi4tin** [comment]
```
dsfdsf
dsfs
    if 
```

**Comment by mi4tin** [comment]
> Python是对空格对齐敏感的语言。对齐会影响程序执行顺序。break执行时是在小于n的i整除n的时候。建议笑来老师在这个例子中说明。
> @mi4tin 贴python代码的时候用键盘波浪线下(tab键上方)前后三个"`"包起来。你贴的代码没法看出执行逻辑。
> 
> ```
> for n in range(2, 100):
>     if n == 2:
>         print(n)
>         continue
>     for i in range(2, n):
>         if (n % i) == 0:
>             break
>     print(n)            # 事实上相当于针对 range(2, 100) 中每个 n 都执行了一次 print(n)
>                         # 这个 print(n) 属于语句块 for n in range(2, 100):
> ```

thank you
