### ISSUE TITLE
本书在线版本

### ISSUE THREAD

**Issue by wangyan** [selfteaching/the-craft-of-selfteaching#354]
地址：[https://www.yuque.com/wangyan/the-craft-of-selfteaching](https://www.yuque.com/wangyan/the-craft-of-selfteaching)

在线版本主要是为了方便移动端阅读，该版本非实时更新，自然也没有 JupyterLab 丰富的交互功能。有需要的朋友可以扫码阅读一下。

![](https://img.cdn.wangyan.org/s/selfteaching/ercode.png)

**Comment by xiaolai** [comment]
还在不断更新中，所以，外延版本通常会耽误读者。
