### ISSUE TITLE
鸡巴受伤

### ISSUE THREAD

**Issue by glsscnnn** [selfteaching/the-craft-of-selfteaching#373]
兄弟他妈的

<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub For GitHub</a></sub>

**Comment by xiaolai** [comment]
他妈的接着学。

**Comment by sxuya** [comment]
他妈的，硬学，盯着头皮学。

你看，标题都用 English 写的，多好的开始。

**Comment by macheng2017** [comment]
他妈的，我到底是关注一群什么人啊

**Comment by macheng2017** [comment]
哈哈

**Comment by Lihao2017-11-15** [comment]
我想知道是怎么伤的？

**Comment by logan-lieou** [comment]
# 他妈的, 你的女儿
