### ISSUE TITLE
MacOS系统。安装组件时报：command not found: conda

### ISSUE THREAD

**Issue by sunshangyi** [selfteaching/the-craft-of-selfteaching#44]
安装完Anaconda后，开始安装如下组件：
conda update conda
conda update anaconda
conda install -c conda-forge nodejs
conda install -c conda-forge jupyterlab

打开terminal，输入后报错：zsh: command not found: conda

**Comment by HarryYC** [comment]
reboot

**Comment by jiap** [comment]
> 安装完Anaconda后，开始安装如下组件：
> conda update conda
> conda update anaconda
> conda install -c conda-forge nodejs
> conda install -c conda-forge jupyterlab
> 
> 打开terminal，输入后报错：zsh: command not found: conda

你使用的是zsh。
解决方法：
1. 打开终端，在终端输入 `vi ~/.bash_profile`，找到关于conda 的安装内容，将一下内容复制，按 `Esc`，并输入 `:q!` 退出。
```
# >>> conda init >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$(CONDA_REPORT_ERRORS=false '/anaconda2/bin/conda' shell.bash hook 2> /dev/null)"
if [ $? -eq 0 ]; then
    \eval "$__conda_setup"
else
    if [ -f "/anaconda2/etc/profile.d/conda.sh" ]; then
        . "/anaconda2/etc/profile.d/conda.sh"
        CONDA_CHANGEPS1=false conda activate base
    else
        \export PATH="/anaconda2/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda init <<<
```

2. 在终端输入 `vi ~/.zshrc`，将上述内容粘贴，退出并`:wq`保存。

3. 终端输入 `source ~/.zshrc` 执行，之后就可以了。

**Comment by rainyuzi** [comment]
我的终端是 iTerm2，安装了 zsh 和 oh-my-zsh，自此，我打开命令行的时候不在执行~/.bash_profile，如果要想让这个文件有效，那么修改 zsh 的配置文件：
编辑~/.zshrc，在文件里加入一行：
```source ~/.bash_profile```
