### ISSUE TITLE
如果能弄成gitbook就太好了

### ISSUE THREAD

**Issue by ruanwenjun** [selfteaching/the-craft-of-selfteaching#452]

**Comment by xiaolai** [comment]
不太好。我以前就用过 gitbook，到最后，只有展示功能 —— 这不是现代出版。互动功能才是重要的。

**Comment by ruanwenjun** [comment]
也对，能发表评论太重要了

**Comment by hantsy** [comment]
@xiaolai 

Gitbook 支持从 Github 同步。

 @ruanwenjun   

Gitbook也支持评论。
