### ISSUE TITLE
关于修改“Part.1.E.2”中一条代码示例的小建议

### ISSUE THREAD

**Issue by richardchen0954** [selfteaching/the-craft-of-selfteaching#453]
本书在 `Part.1.E.2.values-and-their-operators.ipynb/操作符/布尔值操作符` 处，示例了如下代码来说明布尔值操作符的优先级，

> True and False or not True

结合下面的文字讲解， 与或非 的优先级一目了然。

但，巧合在于，在该示例中， `not` 运算在该位置只有一种运算可能（机会），即末尾的 `not True`，而 ` ((True and False) or not True) == (True and (False or not True))` 返回结果为 `True` ，即，不论我们假定 与或非 谁的优先级高，该示例运算结果都相同，愚以为，如果将示例稍作改动，让不同优先级假设下的结果不同，读者就可以通过简单尝试，对优先级做出一些验证，这样可能会略微有那么一丢丢好处。例如，改为

> not False or True and False

`(not False or (True and False)) == (not (False or True) and False)` 返回结果为 False 。

**Comment by xiaolai** [comment]
我觉得可以，提交 pull request 吧。

**Comment by xiaolai** [comment]
尝试着写了一下说明，发现更容易让读者糊涂。原来的也没有毛病。

**Comment by richardchen0954** [comment]
果然，后者反而不适合把事情说明白。没提交PR就是有点顾虑这个说明的部分。这写给别人看的内容果然不能光满足自己的yy，哈哈。
