### ISSUE TITLE
麻烦介绍下windows下面anaconda和jupyterlab的安装

### ISSUE THREAD

**Issue by zhaosky** [selfteaching/the-craft-of-selfteaching#46]
用Mac电脑的毕竟少数，用windows系统的更多，为什么不介绍下windows下面anaconda和jupyterlab的安装。非要用蹩脚的命令行在mac上面安装呢？

**Comment by xiaolai** [comment]
windows 下的安装，在 anaconda 官网上有，很清楚。去看看吧。另外，啥叫“蹩脚的命令行”？

**Comment by JiangTianZheng** [comment]
赞美笑来老师的涵养

**Comment by xiaowutongxue2019** [comment]
笑来老师，在本地配置jupyterlab的路上卡住了，网上搜了一圈安装的帖子，尝试了都没成功，哪里有详细Windows安装教程了

**Comment by zhaosky** [comment]
做软件开发的，对用户交互这块毕竟敏感，知道笑来老师的意思。不过对小白来说确实挺困难的。我们很多时候给技术支持一些命名行他们都搞不定。所以我称为“蹩脚的命令行”

**Comment by zhaosky** [comment]
> windows 下的安装，在 anaconda 官网上有，很清楚。去看看吧。另外，啥叫“蹩脚的命令行”？
做软件开发的，对用户交互这块毕竟敏感，知道笑来老师的意思。不过对小白来说确实挺困难的。我们很多时候给技术支持一些命名行他们都搞不定。所以我称为“蹩脚的命令行”

**Comment by zhaosky** [comment]
> windows 下的安装，在 anaconda 官网上有，很清楚。去看看吧。另外，啥叫“蹩脚的命令行”？



> 笑来老师，在本地配置jupyterlab的路上卡住了，网上搜了一圈安装的帖子，尝试了都没成功，哪里有详细Windows安装教程了

就是下一步啊，

**Comment by xiaowutongxue2019** [comment]
谢谢回复，小白还在https://www.anaconda.com/的网站上摸索

**Comment by xiaolai** [comment]
https://www.google.com/search?q=anaconda+windows+install

https://docs.anaconda.com/anaconda/install/windows/

不过，你更应该先去看看这篇：

https://github.com/selfteaching/the-craft-of-selfteaching/blob/master/Part.3.G.the-golden-age-and-google.ipynb

**Comment by zyt9812** [comment]
刚解决 用anconda prompt 代替terminal
在win 系统下  下载anaconda安装 然后在开始菜单 anaconda3 下面找到“anaconda prompt”
双击打开 出来一个 黑底色的框
后面就和打开 terminal 要 conda update的那4个命令一样了。

当然我前面走了些弯路（或许不是）在“anaconda prompt”窗口用这个命令安装的 pip install jupyterlab
我觉得升级命令即可  要启动jupyter lab的话在“anaconda prompt”窗口 输入jupyter lab 命令

**Comment by chargemyself** [comment]
大概是要了解一下在win下面的指令。安装好anaconda之后，就是用anaconda下面的的anaconda prompt来操作了。

**Comment by zhaosky** [comment]
谢谢笑来，不过我看他们很多google都用不成吧。我提取了下( **anaconda+windows+install**)的关键词，大家可以用百度试下。

**Comment by zyt9812** [comment]
用命令行的效率更高点  我以前打魔兽的时候别人也说我用快捷键装X，其实就是效率高嘛。
笑来老师一直用苹果系统的，so。有这个价位的老师免费教还有啥不满足的。
虽然我也很生气，买了个苹果还被老婆拿走了，现在想想小红点比触摸板好用，联想不争气啊。

**Comment by zhaosky** [comment]
笑来老师跨界还是有风险的，感觉没大牛的技术博客写的清楚，所以说一下。但是来github，是你拥抱开源，不是贴着脸说免费，又没人让你免费。 @zyt9812

**Comment by zhaosky** [comment]
另外给那些不经常用github的宣贯下，issue多证明关注度高。没人用没人看才没issue。开源面前大家都是主人翁的态度。

**Comment by slona-song** [comment]
> > windows 下的安装，在 anaconda 官网上有，很清楚。去看看吧。另外，啥叫“蹩脚的命令行”？
> > 做软件开发的，对用户交互这块毕竟敏感，知道笑来老师的意思。不过对小白来说确实挺困难的。我们很多时候给技术支持一些命名行他们都搞不定。所以我称为“蹩脚的命令行”



> 刚解决 用anconda prompt 代替terminal
> 在win 系统下 下载anaconda安装 然后在开始菜单 anaconda3 下面找到“anaconda prompt”
> 双击打开 出来一个 黑底色的框
> 后面就和打开 terminal 要 conda update的那4个命令一样了。
> 
> 当然我前面走了些弯路（或许不是）在“anaconda prompt”窗口用这个命令安装的 pip install jupyterlab
> 我觉得升级命令即可 要启动jupyter lab的话在“anaconda prompt”窗口 输入jupyter lab 命令

我就是点开anaconda prompt试了一下，一切都很顺利，但是jupyter lab 一直打不开，只能用jupyter notebook

**Comment by zhaosky** [comment]
> > > windows 下的安装，在 anaconda 官网上有，很清楚。去看看吧。另外，啥叫“蹩脚的命令行”？
> > > 做软件开发的，对用户交互这块毕竟敏感，知道笑来老师的意思。不过对小白来说确实挺困难的。我们很多时候给技术支持一些命名行他们都搞不定。所以我称为“蹩脚的命令行”
> 
> > 刚解决 用anconda prompt 代替terminal
> > 在win 系统下 下载anaconda安装 然后在开始菜单 anaconda3 下面找到“anaconda prompt”
> > 双击打开 出来一个 黑底色的框
> > 后面就和打开 terminal 要 conda update的那4个命令一样了。
> > 当然我前面走了些弯路（或许不是）在“anaconda prompt”窗口用这个命令安装的 pip install jupyterlab
> > 我觉得升级命令即可 要启动jupyter lab的话在“anaconda prompt”窗口 输入jupyter lab 命令
> 
> 我就是点开anaconda prompt试了一下，一切都很顺利，但是jupyter lab 一直打不开，只能用jupyter notebook

我在简书上找到一篇介绍，好像要手动更新jupyter_core和jupyter_client。在Anaconda Prompt中输入
```
conda update jupyter_core jupyter_client
```

**Comment by apkkids** [comment]
@zhaosky @xiaolai 
windows下面anaconda和jupyterlab的安装步骤

### 一、安装
1. 在此地址寻找windows版本anaconda下载：
https://www.anaconda.com/distribution/#download-section
或者直接下载当前最新版本
https://repo.anaconda.com/archive/Anaconda3-2018.12-Windows-x86_64.exe
2.双击安装，一路next即可，也可根据自己的情况修改某些配置项
3.安装到最后一步，会问你是否要安装微软出品的 Visual Studio Code，点击“Install MicroSoft VSCode”按钮

### 二、更新
1.在开始菜单中找到并打开Anacoda Prompt，会弹出一个bash界面
2.依次输入如下命令
> conda update conda
conda update anaconda
conda install -c conda-forge nodejs
conda install -c conda-forge jupyterlab # 这是用来升级 jupyter lab 到最新版的方法

3.确认安装成功，输入如下命令

> python --version
node -v
jupyter lab --version
jupyter notebook --version
pip --version

### 三、配置
1.在Anacoda Prompt中cd进入Jupyter lab的安装目录，例如 C:\Users\USER_NAME\.jupyter，输入下列命令：
> jupyter lab --generate-config

这会在 C:\Users\USER_NAME\.jupyter目录下生成一个 jupyter_notebook_config.py 文件。
然后

> cd  C:\Users\USER_NAME\.jupyter
code jupyter_notebook_config.py

上面的 code 命令，需要你已经安装 Visual Studio Code，并且在已经在其中设置了 Install 'code' command in PATH。事实上，你可以用你喜欢的任何编辑器打开 jupyter_notebook_config.py 文件。

文件内容很长，有空可以仔细看。可以直接将以下内容拷贝粘贴到文件底部，根据需求修改：

> #c.NotebookApp.token = ''
#c.NotebookApp.open_browser = False
#c.NotebookApp.notebook_dir = '~/'
#c.NotebookApp.default_url = '/tree'

### 四、运行Jupyter lab
打开 Anacoda Prompt，cd 到你想打开 Jupyter lab 的目录（就是你保存 ipynb 文件的地方，以便在 Jupyter lab 中打开、浏览、编辑 ipynb 文件），在这里以用户根目录为例 C:\Users\USER_NAME：

> cd C:\Users\USER_NAME
jupyter lab

此时的  Anacoda Prompt 窗口不能关闭，否则 Jupyter lab 就停止运行了 —— 就将它放在那里。
随后会有个浏览器打开，指向 http://localhost:8888/lab? —— 你就看到 Jupyter lab 的操作界面了。
![360截图1675110195118119](https://user-images.githubusercontent.com/11962113/54433786-a2cc1c80-4767-11e9-9cc5-fe0b162ba0c3.png)

目前，Jupyter lab 和 Jupyter notebook 是并存的，虽然前者是后者的下一步替代者。如果你依然习惯于使用 Jupyter notebook，那么，在浏览器中指向 http://localhost:8888/tree? 看到的就是 Jupyter notebook，如下图所示：
![360截图16430914897378](https://user-images.githubusercontent.com/11962113/54433829-c000eb00-4767-11e9-8465-95b27d522b2b.png)
### 五、说明
其余部分，请参考https://github.com/apkkids/the-craft-of-selfteaching/blob/master/T-appendix.jupyter-installation-and-setup.ipynb
