### ISSUE TITLE
添加更好的表述:用电路开关的串并联来理解布林运算

### ISSUE THREAD

**Issue by LayCarpenter** [selfteaching/the-craft-of-selfteaching#477]
用**电路图**的串联和并联来理解布林运算
比只用**表格**或**韦恩图**更形象更易理解哦

- True表示开关闭合(通)

- False表示开关断开(不通)

- and表示开关的串联,只有都True(闭合),电路才通(True)

- or表示开关的并联,只要一个True(闭合),电路就通(True)

- not的电路图怎么描述我就不懂了, 直接记成表示"不" 可以吗? 不True(闭合)即False(断开)

![两个开关串联](https://user-images.githubusercontent.com/24835885/55270512-71605e80-52da-11e9-842d-f0657e7b83c2.jpg)
![两个开关并联](https://user-images.githubusercontent.com/24835885/55270513-72918b80-52da-11e9-9fb3-9f41d66c3dbd.jpg)

**Comment by xiaolai** [comment]
借用一个“陌生”概念，类比另一个“陌生概念”，不是好办法。

**Comment by LayCarpenter** [comment]
### 电路图不是陌生的而是熟悉的哦，这也不是类比而是香农的开关电路理论。


- 电路图（串联并联）是在初中物理的内容，而高中才文理分科，所以，不管是理科生还是文科生，电路图不应该是陌生的哦。我明白李老师的意思，要用熟悉的已知的帮助读者去理解陌生的未知的。电路图就是熟悉的哦。

- 电路图不是类比哦，而是本质哦，因为这是香农的开关电路理论——开关电路和布林运算是等价的。

> 克劳德·香农（Claude Elwood Shannon）发表那篇著名论文，[A SYMBOLIC ANALYSIS OF RELAY AND SWITCHING CIRCUITS](https://www.cs.virginia.edu/~evans/greatworks/shannon38.pdf) 之后，布尔代数才算是开始被大规模应用到实处。

下图是香农论文 A SYMBOLIC ANALYSIS OF RELAY AND SWITCHING CIRCUITS 的截图——**开关电路和布林运算的等价关系。**
<img width="703" alt="开关电路和布林运算的等价关系" src="https://user-images.githubusercontent.com/24835885/55285214-ddfe5a80-53b9-11e9-8d3a-1420b81fad5c.png">

> in parallel with 并联

> in series with   串联 

下面这句引自《吴军·科技史纲60讲》48| 计算机的本质：重新理解摩尔定律和信息时代
> 今天所有的集成电路里面其实都是各种各样的开关电路。




哈哈 李老师被说服了么？

**Comment by xiaolai** [comment]
看到了。这不用被说服。类比这么用效率低。

**Comment by LayCarpenter** [comment]
感恩笑来老师拨冗回复，希望我下次能真正帮上忙。
