### ISSUE TITLE
李老师如何通过这本书变现呢？

### ISSUE THREAD

**Issue by LALINUX2019** [selfteaching/the-craft-of-selfteaching#480]
难道这么好的内容没有变现的价值么？

**Comment by LALINUX2019** [comment]
或者说 本书对于老师的最大作用，就是维护公共形象？

**Comment by xiaominglui** [comment]
> 难道这么好的内容没有变现的价值么？

李老师提过本书会出版，这应该是变现途径之一

**Comment by LALINUX2019** [comment]
> > 难道这么好的内容没有变现的价值么？
> 
> 李老师提过本书会出版，这应该是变现途径之一

那为何不直接出版嘞？

说不定能卖的更多

（如果出版了，就不是交互式学习了欸）

**Comment by xiaolai** [comment]
怎么变现是我的事儿哦。

**Comment by zhouqiling** [comment]
谢谢老师！

**Comment by HHJluoluo** [comment]
免费就是这本书最大的价值。

**Comment by sxuya** [comment]
按照笑来老师的回复，感觉，有些是价值，不是所有人能看得到的，可能笑来老师看到变“现”，我们是看不出来的，而我们在意的变现很可能不是笑来老师在意的，而这个就是思想上差距鸿沟，可怕。

要不断学习。

**Comment by huanbowine** [comment]
> 按照笑来老师的回复，感觉，有些是价值，不是所有人能看得到的，可能笑来老师看到变“现”，我们是看不出来的，而我们在意的变现很可能不是笑来老师在意的，而这个就是思想上差距鸿沟，可怕。
> 
> 要不断学习。

认知圈层不同，我们在沟通中提的问题就不同了。

**Comment by HarryYC** [comment]
人生三大坑之一：操碎了别人的心肝

**Comment by LALINUX2019** [comment]
> 人生三大坑之一：操碎了别人的心肝

真是一不小心就掉进去了呢哈哈哈
