### ISSUE TITLE
Part.1.E.6.containers

### ISSUE THREAD

**Issue by zechuhe** [selfteaching/the-craft-of-selfteaching#481]
410 行 "del s[3]  # 这一句会报错"
建議修改為 del s[2]
因為 s = 'Python'[2:5] 只會剩下 tho ， s[3] 不存在

**Comment by xiaolai** [comment]
所以才会报错啊……

**Comment by zechuhe** [comment]
> 所以才会报错啊……
我的理解，您要表達的意思是「列表（List）是可变序列，而字符串（str）是不可变序列」
因此若將其變成 List ，就要可以刪減
```
s = 'Python'[2:5]
print(s)
w=list(s)  #將 s 轉成 list w
del w[3]  #若依然是 [3] 的話此時會報錯 
IndexError: list assignment index out of range
```
我相信這不是您要表達的；
故建議改成 s[2] 是因為，若此時 s 是 list 的話，del  s[2] 就會剩下 ['t', 'h']
才能將焦點著重在" list 可刪減元素、str 則否 "

**Comment by xiaolai** [comment]
OK
