### ISSUE TITLE
关于 Part.3.B.3 的修改建议

### ISSUE THREAD

**Issue by richardchen0954** [selfteaching/the-craft-of-selfteaching#579]
1.  该部分所有（共三处）`sep=', '`，可能都需要替换成`end=', '`，或者干脆删掉；
1.  位置：3.b.3/1.2生成器
原文：`生成器函数被 next() 调用后，执行到 yield 生成一个值返回（然后继续执行剩余的语句）...`
改为：...（然后 next() 后剩余的语句继续执行）...
原因：
（执行到 yield 生成一个值返回后），“剩余的语句”易被误解为 yield 后剩余的语句（且原文中“然后继续执行”的主语应该还是“生成器函数”），实则 yield 后剩余语句并未执行， next() 后剩余语句继续执行，直到下一次执行 next() ，生成器函数继续执行 yield 后剩余语句直到下一个 yield 。反正我第一次读是误解了这里...
![bug2](https://user-images.githubusercontent.com/24580978/55671463-d4498b00-58c2-11e9-87f0-c8c97cf74f31.png)
1.  图中箭头处存在对齐问题。但不影响代码运行好像。。。
![bug3](https://user-images.githubusercontent.com/24580978/55671739-b29dd300-58c5-11e9-9c80-f50097452727.png)

**Comment by xiaolai** [comment]
1. 不用改；
2. 改过了。
3. 为啥要缩进 3 个空格？而不是 4 个空格？

**Comment by richardchen0954** [comment]
关于3，我没说清楚哈，这个截图是一张图，就是原书稿（commit 到 a432b0e）在网页中打开后的截图，原稿在箭头处就是3个空格的缩进，而多截了上面的代码出来只是做对比用的。而且我这边在 jupyter lab打开后，三个缩进会显示红色字体（见图）。但是呢，这个缩进其实没有啥硬性要求好像，反正都能用，不过跟其他地方的缩进不太统一罢了 。
![bug33](https://user-images.githubusercontent.com/24580978/55685297-01f80800-5987-11e9-93eb-9d923f5cd7ab.png)
