### ISSUE TITLE
难受：创建新文件的语法是 open()

### ISSUE THREAD

**Issue by sxuya** [selfteaching/the-craft-of-selfteaching#609]
为什么是 open()，对于中文用户的新手来说真的很费解，open() 是打开嘛，不是应该有文件之后才能打开么，没有文件不是应该先创建（new 或者 create）一个文件、然后在打开（open）么？

这个和电脑对于文件的操作逻辑不同呀，为什么会这么设计呢？

**Comment by xiaolai** [comment]
：）
