### ISSUE TITLE
vsCode运行程序报错

### ISSUE THREAD

**Issue by 2282472436** [selfteaching/the-craft-of-selfteaching#733]
每次运行程序时都会报“Commond Not Found Error”错误，到网上找也找不到相同的问题，请问各位到底该怎么解决？
![vsCode](https://user-images.githubusercontent.com/46254827/56863761-ee234d00-69ec-11e9-81a9-ebd43e8c9bcf.png)

**Comment by wpeiran** [comment]
报错提示给出的就是解决方案。在终端按提示执行代码试试。

**Comment by Teachme2hax** [comment]
Please....im sorry whoever i made mad or whats going on but.....pls like help make it stop....

**Comment by Teachme2hax** [comment]
I unsubscribed bc i am not abke tk contribute

**Comment by 2282472436** [comment]
已解决，因为报错中写了未“conda activate”,参考了以下链接来配置python环境
https://www.jianshu.com/p/f10fb1a4cc87
之后再初始化内核（事实上是重新选了,因为原来是bash）成powershell，成功执行，未报错，就是运行有点慢...
