### ISSUE TITLE
单元格的内容双击后，就恢复不了了，格式都乱了

### ISSUE THREAD

**Issue by Zander2014** [selfteaching/the-craft-of-selfteaching#734]
如题
单元格的内容是格式化的，双击后，就恢复不了了，格式都乱了，只能关闭页签，再打开，好麻烦，感觉双击是一种习惯，很容易就操作到。

**Comment by Zander2014** [comment]
补充一下，在lab模式下

**Comment by wpeiran** [comment]
单个markdown单元格恢复渲染样式的方法是：
1、按Esc回到命令模式;
2、选中要恢复渲染的单元格;
3、按`Shift + Enter`。
就会重新恢复渲染样式。和执行代码一个道理，markdown单元格是执行渲染。

**Comment by Zander2014** [comment]
> 单个markdown单元格恢复渲染样式的方法是：
> 1、按Esc回到命令模式;
> 2、选中要恢复渲染的单元格;
> 3、按`Shift + Enter`。
> 就会重新恢复渲染样式。和执行代码一个道理，markdown单元格是执行渲染。

非常感谢！
