### ISSUE TITLE
李笑来老师是否考虑做一些视频教程？

### ISSUE THREAD

**Issue by Alxead** [selfteaching/the-craft-of-selfteaching#77]
我想对于在电脑上的操作来讲，看实实在在的视频演示比阅读文字效率估计要高10倍。

**Comment by xiaolai** [comment]
效率低十倍吧？各人看法习惯不同。

**Comment by zhaosky** [comment]
没有，对于本书来书，用Jupyterlab互动性已经很强了

**Comment by linxixizhi** [comment]
用过视频课程，感觉节奏多半由讲授者掌控——与自学这个主题冲突了。如果电脑屏幕比较小，或者平台视频系统做得不够好，那就更麻烦了。

而且，“好的”视频课有一种特点：短短40分钟，就让你觉得收获满满，学了很多。

**Comment by zdy958** [comment]
我们可以自己录制自学视频发到网上交流学习，但是视频还是辅助，主要还是阅读。

**Comment by cuglws** [comment]
笑来老师游泳都是通过自学而来，可想而知书籍的力量是无穷的

**Comment by liushooter** [comment]
俗话说万事开头难，**对于小白来说**，安装、配置环境可以说是最大的槛儿。
看了下现在的issue，讨论环境的有很多内容。
在线下培训过很多零基础小白，配置环境时间要占到整个活动的一半儿左右。
大部分用户是 **Window用户**，个人电脑配置千差万别，还有国内特殊的网络环境等，

**做个配置环境的视频内容就足够了**， Window为重点，Mac次之，Linux用户再次之，
做好并不容易哦。

知识的力量是无穷的，载体赋予知识新的活力，你看《流浪地球》电影跟读小说的观感差很多，
科教片有越来越多的iMax格式，成本不一样，带来的效果也不一样。
