### ISSUE TITLE
jupyterbook能直接运行里面代码是吗，要怎么配置，操作呢？

### ISSUE THREAD

**Issue by huazi1234** [selfteaching/the-craft-of-selfteaching#792]

**Comment by RanchoGao** [comment]
在 最后的 Jupyterlab 的安装与配置章节里有提到，自己阅读、跟着操作就知道了

**Comment by sxuya** [comment]
对，楼上说的没错，项目里面有一张详细的说明，实在看不懂，下载的时候就在官方网站嘛，看下一简单的说明；再次一些的方法，到 哔哩哔哩 等视频网站找一些视频教程看一下就好了（但是不建议），文字教程已经很棒了。

**Comment by huazi1234** [comment]
多谢楼上两位了
