### ISSUE TITLE
“我写过的一本书”，微信链接无法查看

### ISSUE THREAD

**Issue by gantrol** [selfteaching/the-craft-of-selfteaching#81]
Part.3.G中，[我写过的一本“书”，发布在网上](https://mp.weixin.qq.com/s?__biz=MzAxNzI4MTMwMw==&mid=210678304&idx=1&sn=e4f46f8ba31ba9b87e3ab9f5b045f190&scene=2&srcid=0921CIdp1y5LZY7oWqWAsi85&from=timeline&isappinstalled=0#rd)，显示`此内容因违规无法查看`

**Comment by xiaolai** [comment]
嗯，不知道哪个王八蛋举报了，竟然给屏蔽了。我推到 github 上了。

**Comment by zhzja** [comment]
呵呵，难怪人民网股价那么牛，业绩那么好，逼着肉身翻墙吗？

**Comment by wenjunmo** [comment]
我是莫文俊，邮件已经收到了，谢谢你。
