### ISSUE TITLE
Part.1.E.2.values-and-their-operators.ipynb无法打开

### ISSUE THREAD

**Issue by shao-shuai** [selfteaching/the-craft-of-selfteaching#91]
![image](https://user-images.githubusercontent.com/28980017/54450483-b9458a00-470d-11e9-93b4-0f99fcc061e4.png)

求助，E.2.无法打开。

**Comment by junty90** [comment]
Duplicate of #89 已修复，请更新。

**Comment by shao-shuai** [comment]
@junty90 感谢
