### ISSUE TITLE
请教：reversed后，迭代容器的结果为什么不是按字母逆序排列呢？

### ISSUE THREAD

**Issue by woohello** [selfteaching/the-craft-of-selfteaching#969]
t = ('bob', 'ann', 'john', 'mike', 'joe')
for i, t in enumerate(reversed(t)):
    print(i, t)
0 joe
1 mike
2 john
3 ann
4 bob

这个结果没理解是为什么？

**Comment by alichenxiang** [comment]
我理解 `reversed()` 的作用是翻转 t 这个 tuple (也可以是List）里每一个元素的顺序。

**Comment by woohello** [comment]
good。reversed并不排序的
