### ISSUE TITLE
笑来老师这是个什么项目？ 单单讲python教程吗？！

### ISSUE THREAD

**Issue by dshowing** [selfteaching/the-craft-of-selfteaching#98]

**Comment by zhzja** [comment]
看看就知道咯，通过这个逼着大家自学很多东西呢…… 一如既往，关注学习，今天还重新看了一下2016的文章，自己做的还不够，最近申请出国留学，才发现自己能力如果早几年就做好准备，现在会好多了…… 虽然那时候一直忙上班…… 想不到2018后改变那么多…… 我已经38岁高龄了，😄 重新拿起26年的编程

**Comment by linxixizhi** [comment]
以Python为例，讲自学
